### ISSUE TITLE
Stage Failed. Missing receipt 'E:\GameDEV\Pseudoregalia\pseudo-menu\Binaries\Win64\pseudoregalia.target'

### ISSUE THREAD

**Issue by Luma48** [pseudoregalia-modding/pseudo-menu#2]
Heya I was wondering if you know why the Stage part of my cook fails:
![image](https://github.com/user-attachments/assets/f00174a9-f00a-4ee1-928d-3a5ced6c97f6)
![image](https://github.com/user-attachments/assets/5fba0aef-e473-449a-a3a8-0cbea13c5f81)
I'm a bit confused as to why it's looking for a Binaries folder in my pseudo-menu folder. If you know what the issue is that would be great! If not a reply to this would also be much appreciated as maybe we could discuss it further! I'm kinda new to UE btw so sorry if this is an obvious question!

**Comment by turncoda** [comment]
Thanks for the report. Fixed in 96222c3
